name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_ID = "Ov23lisiIfmj0L3L7CIg"
GITHUB_OWNER = "lea0518"
GITHUB_REPO = "NavSphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://navsphere-eyn.pages.dev/api/auth"
NEXT_PUBLIC_API_URL="https://navsphere-eyn.pages.dev"

